### PR TITLE
Coveralls support

### PR DESCRIPTION
**Pull request by gdamore**
This is primarily coveralls support for code coverage reporting in Travis.

### CODE REVIEW

**Comment by gdamore** [comment]
Please hold up on this.

**Comment by gdamore** [comment]
Ok, it's all good now.  Turns out that the YAML was all screwed up.  This is based on *top* of the stuff in the garrett branch, and should apply cleanly immediately thereafter.  The last two commits are the only ones that this PR adds.

**Comment by gdamore** [comment]
I will rebase this... apparently there are conflicts... hang on.

**Comment by gdamore** [comment]
Wait for the CI to finish, but then we should go ahead and merge. :-)

**Comment by achille-roussel** [comment]
Perfect 👍

**Pull request merged**
