### PR TITLE
This fixes environment variables used by travis.

### PR DESCRIPTION
**Pull request by gdamore**
Don't merge this yet -- I want to wait for Travis to complete so I can see if my changes work.

### CODE REVIEW

**Comment by gdamore** [comment]
Ok, I just checked, and its doing the right things.

FWIW, it looks like the code coverage stuff only gets uploaded on branches from the master.  I think this is to protect the token.  Otherwise I could create a PR that takes the token from the environment and prints it to the log, or just emails it to me... and I don't have to be a member of the org or an admin to do that!

Presumably orgs are watching with vigilance over code integrations that might try to expose the token in a commit, and not merging such code to master.

**Comment by gdamore** [comment]
Btw, please merge this -- *after* the other one.

**Comment by f2prateek** [comment]
Should I rebase this?

**Comment by gdamore** [comment]
should not have to.  :)

**Comment by f2prateek** [comment]
Done!

**Pull request merged**
